name: Setup SDE
description: Downloads Intel's SDE binaries.
author: Petar Petrov and contributors
branding:
  icon: play
  color: green
inputs:
  environmentVariableName:
    description: Environment variable name for SDE binaries path
    defaultValue: SDE_PATH
    required: true
  sdeVersion:
    description: "Intel SDE version (examples: 9.14.0, 9.7.0, 9.0.0, 8.69.1)"
    defaultValue: 9.14.0
    required: true
runs:
  using: node12
  main: dist/index.js
