name: Setup SDE
description: Downloads Intel's SDE binaries.
author: Petar Petrov and contributors
branding:
  icon: play
  color: green
inputs:
  environmentVariableName:
    description: Environment variable name for SDE binaries path
    defaultValue: SDE_PATH
    required: true
  sdeVersion:
    description: "Intel SDE version (examples: 9.58.0, 9.33.0)"
    defaultValue: 9.58.0
    required: true
runs:
  using: node20
  main: dist/index.js
