name: Setup SDE
description: Downloads Intel's SDE binaries.
author: Petar Petrov and contributors
inputs:
  environmentVariableName:
    description: Environment variable name for SDE binaries path
    defaultValue: SDE_PATH
    required: true
runs:
  using: node12
  main: build.js