name: 'Setup SDE'
description: 'Downloads Intel's SDE binaries.'
inputs:
  test:
    description: 'Environment variable name for SDE binaries path'
    required: true
runs:
  using: 'node12'
  main: 'index.js'