name: Build

on: [push]

jobs:
  build:
    name: Platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # , ubuntu-latest, macOS-latest]
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup SDE
       uses: petarpetrovt/setup-sde@feature/env
       with:
         environmentVariableName: TEST_SDE_PATH

     - name: Assert TEST_SDE_PATH
       run: echo $TEST_SDE_PATH
