name: Build

on: [push]

jobs:
  build:
    name: Platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
     - uses: actions/checkout@v1
     - uses: ./.github/actions/setup-sde