name: Run
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
     - name: Run
       uses: petarpetrovt/setup-sde@main
       with:
         environmentVariableName: TEST_SDE_PATH

     - name: Test
       run: npm run test TEST_SDE_PATH
